services:
  java-spring:
    build: .
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/my-db
      USER : root
      PASSWORD: root
    networks:
      - spring-network
  
  db:
    image: mysql:8.0.33
    restart: always
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-db
    volumes:
      - my-vol:/var/lib/mysql
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
    
volumes:
  my-vol:
    