spring:
  application.name: tp
  datasource:
    url: ${DB_URL}
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
         dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
server:
   port: 8080